apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  template:
    spec:
      volumes:
      - name: jenkins-persistent-storage
        emptyDir: null
        gcePersistentDisk:
          pdName: jenkins-persistent-storage
